### ISSUE TITLE
Get medietree as addon

### ISSUE THREAD

**Issue by thiroxx** [mrfixit2001/rockchip-kernel#7]
Hey could you please compile media tree as addon? Can’t get it to work for myself.

**Comment by mrfixit2001** [comment]
Can you please provide some more detail as to what you're trying to accomplish? "Media tree" is quite broad and includes a LOT of drivers. If you're running into errors or issues please provide detail as to what they are.

**Comment by thiroxx** [comment]
I need drivers for https://www.linuxtv.org/wiki/index.php/Hauppauge_WinTV-quadHD_(DVB-T/T2/C) . Im Running into errors with compilerflags and kernel sources. Maybe you could help? Would really appreciate it.

**Comment by mrfixit2001** [comment]
I haven't forgotten about you - just wanted to reach out. I've been working on my mainline kernel repo. I'm now back to this one. The CX23885 kernel driver in the 4.4 kernel hasn't been touched since 2018, but I just enabled the driver as a module, and it's another example of where rockchip changed stuff and broke things. I'll fix that driver compile and push the updated defconfigs with these settings in my next update. It does appear that the drivers do have the proper settings to apply to the CX23887. Hopefully it works for you.

**Comment by mrfixit2001** [comment]
@thiroxx I've pushed the driver fix so that it compiles. Let me know please, as  I don't have the hardware to test it.

**Comment by mrfixit2001** [comment]
Closing due to no reply
